pagina_estatica:
    pattern: /sitio/{pagina}/
    defaults: { _controller: OfertaBundle:Sitio:estatica }
    
# Ruta completa de la portada (con el slug de la ciudad)
portada:
    pattern: /{ciudad}
    defaults: { _controller: OfertaBundle:Default:portada, ciudad: null, _locale:es }

# Ruta del detalle de oferta
oferta:
    pattern: /{ciudad}/ofertas/{slug}
    defaults: { _controller: OfertaBundle:Default:oferta }
