parameters:
    cupon.codificacion: 'utf-8'

services:
    cupon.utilidades:
        class: Cupon\OfertaBundle\Util\Util
        calls:
            - [ setCodificacion, [%cupon.codificacion%] ]
        #arguments: [@logger, @router]
        
    util:
        alias: cupon.utilidades
        
    cupon.ofertabundle.listener.request:
        class: Cupon\OfertaBundle\Listener\RequestListener
        tags:
             - { name: kernel.event_listener, event: kernel.request }
