ciudad_cambiar:
    pattern: /ciudad/cambiar-a-{ciudad}
    defaults: { _controller: CiudadBundle:Default:cambiar, _locale:es }
    
ciudad_recientes:
    pattern: /{ciudad}/recientes.{_format}
    defaults: { _controller: CiudadBundle:Default:recientes, _locale:es, _format:html }
    requirements:
        _format: html|rss