UsuarioBundle:
    resource: "@UsuarioBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/usuario
    requirements:
        _locale: en|es

TiendaBundle:
    resource: "@TiendaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

CiudadBundle:
    resource: "@CiudadBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

OfertaBundle:
    resource: "@OfertaBundle/Resources/config/routing.yml"
    prefix:   /{_locale}
    requirements:
        _locale: en|es

# Ruta simple de la portada
_portada:
    pattern: /
    defaults: { _controller: OfertaBundle:Default:portada }

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
