security:
    #acl:
    #    connection: default
        
    encoders:
        #Cupon\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations: 10 }
        #Cupon\TiendaBundle\Entity\Tienda: { algorithm: sha512, iterations: 10 }
        Symfony\Component\Security\Core\User\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            users:
                user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
        ## Usuarios del frontend
        #usuarios:
        #    entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
        ## Usuarios de la extranet
        #tiendas:
        #    entity: { class: Cupon\TiendaBundle\Entity\Tienda, property: login }
        ## Usuarios del backend
        #administradores:
        #    users:
        #        # user = admin, pass = 1234
        #        admin: { password: Eti36Ru/pWG6WfoIPiDFUBxUuyvgMA4L8+LLuGbGyqV9ATuT9brCWPchBqX5vFTF+DgntacecW+sSGD+GZts2A==, roles: ROLE_ADMIN }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: /demo/secured/login_check
                login_path: /demo/secured/login
            logout:
                path:   /demo/secured/logout
                target: /demo/
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
