security:
    acl:
        connection: default
        
    encoders:
        Cupon\UsuarioBundle\Entity\Usuario: { algorithm: sha512, iterations:10 }
        #Cupon\UsuarioBundle\Entity\Usuario: plaintext
        #Symfony\Component\Security\Core\User\User: plaintext
        #Cupon\UsuarioBundle\Entity\Usuario:
        #    algorithm: sha512
        #    encode-as-base64: true
        #    iterations: 10
        #Symfony\Component\Security\Core\User\User:
        #    algorithm: sha512
        #    encode-as-base64: true
        #    iterations: 10

    providers:
        usuarios:
            entity: { class: Cupon\UsuarioBundle\Entity\Usuario, property: email }
        #in_memory:
        #    users:
        #        fabricio: { password: fabriciopass, roles: 'ROLE_USUARIO' }

    firewalls:
        frontend:
            pattern: ^/*
            anonymous: ~
            provider: usuarios
            form_login:
                login_path: usuario_login
                check_path: usuario_login_check
            logout:
                path: usuario_logout
                #target: /sitio/vuelve-pronto
                #default_target_path: /usuario/compras
                #always_use_default_target_path: true
            remember_me:
                key: cupon1234
                lifetime: 3600
            switch_user: { role: ROLE_ADMIN }

    access_control:
        - { path: ^/(es|en)/usuario/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(es|en)/usuario/*, roles: ROLE_USUARIO }
    
    role_hierarchy:
        ROLE_ADMIN: [ROLE_TIENDA, ROLE_USUARIO, ROLE_ALLOWED_TO_SWITCH]
